//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandyBug.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Oders = new HashSet<Oder>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage ="Tên tài khoản không được bỏ trống !")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Họ và tên không được bỏ trống !")]
        public string DisplayName { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được bỏ trống !")]
        public string PassWord { get; set; }
        [Required(ErrorMessage = "Email không được bỏ trống !")]
        [EmailAddress(ErrorMessage ="Email không hợp lệ !")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống !")]
        [DataType(DataType.PhoneNumber)]
        public int SDT { get; set; }
        public int Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oder> Oders { get; set; }
    }
}
